Run make again if make -k failed

diff --git a/slaves/linux/tor-ci-linux-GENERIC-extra-arm/build b/slaves/linux/tor-ci-linux-GENERIC-extra-arm/build
--- a/slaves/linux/tor-ci-linux-GENERIC-extra-arm/build
+++ b/slaves/linux/tor-ci-linux-GENERIC-extra-arm/build
@@ -38,5 +38,12 @@ rm -rf build-tree-tor
 mkdir build-tree-tor
 cd build-tree-tor
 ../tor/configure $configure_flags
-make -k ${TOR_JENKINS_MAKEFLAGS:-}
+make -k ${TOR_JENKINS_MAKEFLAGS:-} && rc=0 || rc=$?
+if [ "$rc" != 0 ]; then
+  echo >&2 "============================="
+  echo >&2 "make -k failed.  Re-running without -k to maybe see the error near the end of the build-log."
+  echo >&2 "============================="
+  make ${TOR_JENKINS_MAKEFLAGS:-}
+  exit $rc
+fi
 VERBOSE=yes make -k ${TOR_JENKINS_MAKEFLAGS:-} check
