Do not hardcode list of archs and suite in wrapper scripts

diff --git a/slaves/linux/tor/build-wrapper b/slaves/linux/tor/build-wrapper
--- a/slaves/linux/tor/build-wrapper
+++ b/slaves/linux/tor/build-wrapper
@@ -1,46 +1,34 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 set -x
 set -u
 
-case "${SUITE:-}" in
-	lucid|\
-	natty|\
-	oneiric|\
-	precise|\
-	quantal|\
-	squeeze|\
-	wheezy|\
-	sid)
-		suite="$SUITE"
-		;;
-	*)
-		if [ -z "${SUITE:-}" ]; then
-			echo >&2 "No suite given"
-		else
-			echo >&2 "Invalid suite: $SUITE"
-		fi
-		exit 1
-esac
+check_arg() {
+	name="$1"; shift
+	arg="$1"; shift
 
-case "${ARCHITECTURE:-}" in
-	amd64|\
-	i386)
-		arch="$ARCHITECTURE"
-		;;
-	*)
-		if [ -z "${ARCHITECTURE:-}" ]; then
-			echo >&2 "No arch given"
-		else
-			echo >&2 "Invalid arch: $ARCHITECTURE"
-		fi
+	if [ -z "${arg:-}" ]; then
+		echo >&2 "No $name given"
 		exit 1
-esac
+	fi
+	if [[ "$arg" =~ [^a-z0-9] ]]; then
+		echo >&2 "Invalid $name: $arg"
+		exit 1
+	fi
+}
 
+check_arg "suite" "${SUITE:-}"
+check_arg "architecture" "${ARCHITECTURE:-}"
+
+chroot="$SUITE-$ARCHITECTURE-sbuild"
+if ! schroot -l -c "$chroot" > /dev/null 2>&1; then
+	echo >&2 "Invalid chroot: $chroot"
+	exit 1
+fi
 
 echo "Prepare build environment"
-schroot-wrapper setup "$suite-$arch-sbuild"
+schroot-wrapper setup "$chroot"
 echo "Update package list"
 schroot-wrapper "rootrun" -- "sh" "-c" "(for i in 1 2 3 4 5; do apt-get update && exit 0; sleep 30; done); mkdir -m 0755 -p /usr/share/aclocal"
 echo "Install build dependencies"
