Allow dots in jobnames

diff --git a/slaves/windows/build-wrapper b/slaves/windows/build-wrapper
--- a/slaves/windows/build-wrapper
+++ b/slaves/windows/build-wrapper
@@ -11,7 +11,11 @@ check_arg() {
 		echo >&2 "No $name given."
 		exit 1
 	fi
-	if [[ "$arg" =~ [^A-Za-z0-9-] ]]; then
+	if [[ "$arg" =~ [^A-Za-z0-9.-] ]]; then
+		echo >&2 "Invalid $name: $arg."
+		exit 1
+	fi
+	if [[ "$arg" =~ \.\. ]]; then
 		echo >&2 "Invalid $name: $arg."
 		exit 1
 	fi
