and stem-tor-ci

diff --git a/slaves/linux/stem-tor-ci/build-wrapper b/slaves/linux/stem-tor-ci/build-wrapper
--- a/slaves/linux/stem-tor-ci/build-wrapper
+++ b/slaves/linux/stem-tor-ci/build-wrapper
@@ -1,55 +1,43 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 set -x
 set -u
 
-case "${SUITE:-}" in
-	lucid|\
-	natty|\
-	oneiric|\
-	precise|\
-	quantal|\
-	squeeze|\
-	wheezy|\
-	sid)
-		suite="$SUITE"
-		;;
-	*)
-		if [ -z "${SUITE:-}" ]; then
-			echo >&2 "No suite given"
-		else
-			echo >&2 "Invalid suite: $SUITE"
-		fi
-		exit 1
-esac
+# Stuff that is run in the chroot as root
+setup() {
+	echo "Update package list"
+	for i in 1 2 3 4 5; do
+		apt-get update && break;
+		sleep 30;
+	done;
 
-case "${ARCHITECTURE:-}" in
-	amd64|\
-	i386)
-		arch="$ARCHITECTURE"
-		;;
-	*)
-		if [ -z "${ARCHITECTURE:-}" ]; then
-			echo >&2 "No arch given"
-		else
-			echo >&2 "Invalid arch: $ARCHITECTURE"
-		fi
-		exit 1
-esac
+	echo "Install build dependencies"
+	apt-get install -y python pyflakes tor
+}
+
+# Stuff that is run in the chroot as user
+run() {
+	echo "Cleanup build dir"
+	rm -rf build
+
+	echo "Run unittests"
+	python ./run_tests.py --unit
+
+	echo "Run integration tests against latest tor binary"
+	python ./run_tests.py --tor src/or/tor --integ --target RUN_ALL
+}
 
 
-echo "Prepare build environment"
-schroot-wrapper setup "$suite-$arch-sbuild"
-echo "Update package list"
-schroot-wrapper "rootrun" -- "sh" "-c" "(for i in 1 2 3 4 5; do apt-get update && exit 0; sleep 30; done); mkdir -m 0755 -p /usr/share/aclocal"
-echo "Install build dependencies"
-schroot-wrapper "rootrun" -- apt-get install -y python pyflakes tor
-echo "Cleanup build dir"
-schroot-wrapper "run" -- rm -rf build
-echo "Run unit tests"
-schroot-wrapper "run" -- python ./run_tests.py --unit
-echo "Run integration tests against latest tor binary" 
-schroot-wrapper "run" -- python ./run_tests.py --tor src/or/tor --integ --target RUN_ALL
-echo "Clean up build environment"
-schroot-wrapper "cleanup"
+
+fullpath=$(readlink -f "$0")
+dir=$(dirname "$fullpath")
+common="$dir/../build-wrapper.common"
+for common in "$dir/../build-wrapper.common" "$dir/build-wrapper.common"; do
+	if [ -e "$common" ]; then
+		. "$common"
+		exit 0
+	fi
+done
+echo >&2 "build-wrapper.common not found."
+exit 1
