Rewrite distribution in .changes file

diff --git a/slaves/linux/tor-debian-master-nightly-binaries b/slaves/linux/tor-debian-master-nightly-binaries
--- a/slaves/linux/tor-debian-master-nightly-binaries
+++ b/slaves/linux/tor-debian-master-nightly-binaries
@@ -4,6 +4,31 @@ set -e
 set -x
 set -u
 
+get_metadata() {
+  local dsc="$1"; shift
+
+  dsc="$(readlink -f "$dsc")"
+  local origtar="$(dcmd --orig $dsc)"
+  if ! [ -e "$origtar" ]; then
+    echo >&2 "File $origtar not found"
+    exit 1
+  fi
+
+  local tmpdir="`mktemp -d`"
+  pushd . >/dev/null
+  cd "$tmpdir"
+
+  dpkg-source -x "$dsc" > /dev/null
+  cd */
+
+  local dist=$(dpkg-parsechangelog | grep-dctrl -n -s Distribution '')
+  local ver=$(dpkg-parsechangelog | grep-dctrl -n -s Version '')
+
+  popd >/dev/null
+  rm -rf "$tmpdir"
+  echo "$dist $ver"
+}
+
 rm -rf build
 rm -rf RESULT
 
@@ -33,13 +58,18 @@ esac
 mkdir build
 dcmd ln -v "$dsc" build
 cd build
-sbuild --arch="$ARCHITECTURE" --dist="$SUITE" --nolog --apt-update $extra "$(basename "$dsc")"
+dsc=$(basename "$dsc")
+metadata=$(get_metadata "$dsc")
+read dscdist debian_version <<< "$metadata"
+sbuild --arch="$ARCHITECTURE" --dist="$SUITE" --nolog --apt-update $extra "$dsc"
 
 changes=$(ls -1 *.changes)
 if [ "$(echo "$changes" | wc -l)" != 1 ] || [ -z "$changes" ] ; then
   echo >&2 "Weird number of changes files found."
   exit 1
 fi
+changestool "$changes" setdistribution "$dscdist"
+
 cd ..
 
 mkdir RESULT
